### ISSUE TITLE
Unable to Install / Launch the Bot the First Time

### ISSUE THREAD

**Issue by official-Cromatin** [Midnight-Myth/Mitternacht-NEW#30]
Nach einiger Zeit kam es dazu das der Bot sich nicht mehr Starten Lies bzw Abgestürzt ist (mit ihm leider auch der Host Computer), ich hab Versucht das Problem zu Lösen, leider hab ich auch keinen Error bekommen und somit auch keinen Hinweis was das Problem sein könnte.

Die einzige Option war so nur noch den Bot erneut zu Installieren, als ich Versucht habe ihn das erste mal mit `docker-compose up` zu Starten, hat dies nicht Funktioniert da eine Gewalltige Anzahl von Fehlermeldungen aufgetreten ist
(Der gesammte Fehler ist im Log zu Finden)
[Mitternacht Installer Log.txt](https://github.com/Midnight-Myth/Mitternacht-NEW/files/7997523/Mitternacht.Installer.Log.txt)

Leider hat mein Wissen nicht ausgereicht um den Problemen selbst beizukommen da ich was Bots angeht nocht ganz am Anfang stehe.

Grüße Cromatin

**Comment by expeehaa** [comment]
Der Bot hat einen Prerelease von Discord.Net verwendet, der aus irgendeinem Grund in der Paketquelle nicht mehr verfügbar war. Dann hat dotnet versucht, eine andere Version stattdessen zu verwenden, die aber inkompatibel war.
Ich hab das geupdatet und kompatibel gemacht, sollte also wieder funktionieren.
