### ISSUE TITLE
docker-compose.yml Versions Fehler

### ISSUE THREAD

**Issue by official-Cromatin** [Midnight-Myth/Mitternacht-NEW#34]
Wenn man den Bot Installiert also per Github Pullt und das erste mal mit docker-compose up Starten möchte bekommt man einen Fehler das die Datei docker-compose.yml die Falsche Version enthällt.

Man kann natürlich diese Datei im Editor aufrufen und die Version mauell abändern, jedoch ist das Komplikativ und man muss es bei jeder neu Installation machen.

Es wäre daher von Großem Vorteil wenn man diese Datei im Source Code Anpasst, das würde eine Mänge erleichern

**Comment by expeehaa** [comment]
Was für einen Fehler bekommst du denn und welche Version von docker-compose nutzt du?
Kann sein, dass das damit zusammenhängt. Ich nutze erfolgreich Version 1.28.5. Ich glaube, die aktuellste 1.x funktioniert, 2.x eventuell aber nicht.

**Comment by official-Cromatin** [comment]
Aktuell Verwende ich die Version 1.25.0 von docker-compose

Und das ist der Fehler den ich bekomme:
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by official-Cromatin** [comment]
Lösung:
Ein Downgrade der Version führt zu fehlern, stattdessen sollte man es über pip Versuchen `pip install -U docker-compose` sollte man das noch nicht Installiert haben kann man es über den Paketmanager nachinstallieren `apt install python3-pip` 

Nun sollte man den Bot über docker-compose up ohne fehler starten können

Credits gehen an expeehaa
